/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable @next/next/no-img-element */
import React from 'react';
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { AiFillFacebook, AiFillGithub, AiFillGitlab, AiFillIdcard, AiFillInstagram, AiFillLinkedin, AiFillMail, AiFillTwitterSquare } from "react-icons/ai";
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { ButtonContact } from '../components/Button';
import { ButtonChat } from '../components/Button/ButtonChat';






export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marcos Vini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>

        <div className={styles.content}>


        <Header />
          

          <div className={styles.signSocial}>
            <a href="https://www.facebook.com/Marcos.Code1999/" target="_blank" > <AiFillFacebook /> </a>
            <a href="https://www.instagram.com/marcosviniicode/" target="_blank"> <AiFillInstagram />  </a>
            <a href="https://github.com/marcoscode404" target="_blank"> <AiFillGithub /> </a>
            <a href="https://www.linkedin.com/in/marcos-vini-code-984903181/" target="_blank"> <AiFillLinkedin /> </a>
            <a href="https://blogvinicode.vercel.app/#" target="_blank"> <AiFillIdcard /> </a>
            <a href="https://twitter.com/MarcosV22772662" target="_blank"> <AiFillTwitterSquare /> </a>
            <a href="https://gitlab.com/marcosviniciuspgerogov253" target="_blank"> <AiFillGitlab /> </a>
           
            <a href="marcosviniciuspgerogov253@gmail.com"> <AiFillMail /> </a>
          </div>

        
          <ButtonContact />
          <ButtonChat />
         
        
      </div>
       
       
        
      </main>

            <Footer />

    </div>
  )
}


